version: '3'

services:

    redis:
        image: redis:5-alpine
        container_name: me-redis
        restart: unless-stopped
        ports:
            - 6379
        mem_limit: 2048m
        mem_reservation: 2048m
        logging:
            driver: "json-file"
            options:
                max-size: "2m"

    mysql:
        image: mariadb:10.4
        container_name: me-mysql
        restart: unless-stopped
        ports:
            - 3306
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb_large_prefix=1]
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=changeme
            - MYSQL_DATABASE=lumen
            - MYSQL_USER=lumen
            - MYSQL_PASSWORD=lumen
            - TZ='Europe/Belgrade'
        mem_limit: 2048m
        mem_reservation: 2048m
        logging:
            driver: "json-file"
            options:
                max-size: "2m"

    postgres:
        image: postgres:15.4-alpine
        container_name: me-postgres
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql
        environment:
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_USER=lumen
            - POSTGRES_DB=lumen
            - TZ='Europe/Belgrade'
        mem_limit: 2048m
        mem_reservation: 2048m
        logging:
            driver: "json-file"
            options:
                max-size: "2m"

    backend:
        image: danteyu/nginxunit-php82:dev-2023-08-26.0
        container_name: me-backend
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            - APP_URL=https://localhost/
            - APP_DIR=/opt/workdir/
            - GIT_HOST=${GIT_HOST}
            - GIT_URL=${GIT_URL}
            - GIT_PORT=${GIT_PORT}
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=lumen
            - MYSQL_PASSWORD=lumen
            - MYSQL_USER=lumen
            - MYSQL_PORT=3306
            - TIMEZONE_OFFSET=+00:00
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - SMTP_ENCRYPTION=${SMTP_ENCRYPTION}
            - SMTP_FROM=${SMTP_FROM}
            - SMTP_FROM_NAME=${SMTP_FROM_NAME}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_USER_NAME=${ADMIN_USER_NAME}
            - ADMIN_PHONE_NUMBER=555555555
            - APP_NAME=myappname
            - APP_DEBUG=true
            - APP_TEMP=/tmp/
            - TIMEZONE_LOCAL=UTC
            - ADMIN_FRONTEND_URL=https://localhost/
            - DHUB_FRONTEND_URL=https://localhost/
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_DATABASE=1
            - REDIS_CACHE_DB=2
            - MEX_API_URL=${MEX_API_URL}
            - MEX_API_KEY=${MEX_API_KEY}
            - MAX_EXECUTION_TIME=1800
            - SITE_TRANSLATION_COMMON_CATEGORY_ID=1
            - SITE_TRANSLATION_MAILS_CATEGORY_ID=2
            - MAIL_VERIFY_PEER=false
        volumes:
            - ${WORKDIR}:/opt/workdir
            - ${ID_RSA}:/opt/id_rsa:ro
        depends_on:
            - mysql
            - redis
        mem_limit: 4096m
        mem_reservation: 2048m
        logging:
            driver: "json-file"
            options:
                max-size: "2m"

    adminer:
        image: adminer:standalone
        container_name: me-adminer
        restart: unless-stopped
        ports:
            - 4082:8080
        links:
            - mysql
        depends_on:
            - mysql
        mem_limit: 2048m
        mem_reservation: 2048m
        logging:
            driver: "json-file"
            options:
                max-size: "2m"

volumes:
    mysql-data:
    postgres-data:
